### ISSUE TITLE
Relative file paths

### ISSUE THREAD

**Issue by stevetoro** [GBGitUser/prj-rev-bwfs-dasmoto#1]
https://github.com/GBGitUser/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L13

Nice job downloading your images, storing them in their own `images` folder, and then writing a relative file path to them in your `img` tags.

This will make your project folder much more organized and maintainable and it's better to not depend on a URL that can break or just otherwise make your images unavailable.

**Comment by GBGitUser** [comment]
Cool - thanks Steve.
