### ISSUE TITLE
Page sections

### ISSUE THREAD

**Issue by stevetoro** [GBGitUser/prj-rev-bwfs-dasmoto#2]
https://github.com/GBGitUser/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L12-L15

Nice job putting a space between each of these sections of code so that they stand out even more at first glance.  👍 

Consider wrapping a `div` around each section so that you can properly divide the page into sections. Also, consider giving each `div` the same class `item` or `product` since each section is equivalent. This will help you write more descriptive and concise CSS selectors.

**Comment by GBGitUser** [comment]
Great idea - will do going forward. I'm still trying to find my way was to when and when not to use <div> but as I go through the examples in later units I'm starting to get my head around it.
