### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by stevetoro** [GBGitUser/prj-rev-bwfs-dasmoto#6]
Satisfactory 👍 

Great job reproducing the web page according to the design mock. You've written some nicely organized and readable HTML & CSS as well, good job!

Improve your code by using `div` tags to _divide_ your page into sections. You have three item sections, so you can have a container `div` around each section with a class of `item` or `product`. Improve your code even further by using class names that describe the actual content. Always avoid writing styles in the HTML.

**Comment by GBGitUser** [comment]
Great - thanks Steve - very useful review points. 👍 👍
